### ISSUE TITLE
Can't close app from chrome remote desktop

### ISSUE THREAD

**Issue by fiveseven808** [psychopattt/Discord-Remote#2]
Does not respond to ctrl+alt+f4 command from chrome remote desktop, suggest using another command or alternative exit method such as an always-on-top window with a big stop button to exit the script. That way you can click on something rather than having to push an unobvious key command, as well as give someone a visual indicator that the script is running.

**Comment by psychopattt** [comment]
I changed the shortcut to just `F4`. This makes the command more reliable and _should_ make it work with remote desktop clients.

I'd rather not add an always-on-top window for a few reasons. It would always hide a part of the screen which would make it hard to use some of the commands. Imagine you just want to click something that happens to be behind the window. You would have to click the minimize button of the always-on-top window, then click where you want and then restore the minimized window. The always-on-top window would also appear in every screenshot, which could hide something the user wanted to see in the screenshot. It would again require multiple commands to hide the window, take a screenshot and restore the window. Lastly, if you're using Discord Remote, you're probably unable to see the monitor of the PC you're controlling, so a visual indicator that Discord Remote is running is not really helpful. It would be better to use the `Ping` command.

**Comment by fiveseven808** [comment]
F4 solved the issue! So much easier to troubleshoot remotely. I noticed however that the discord window is constantly in front blocking commands like the click command. I'll create another issue for that though
