### ISSUE TITLE
Discord window is constantly Active and blocks parts of the screen

### ISSUE THREAD

**Issue by fiveseven808** [psychopattt/Discord-Remote#3]
Currently my workflow for this program is to get a screenshot, import into paint to obtain coordinates of where I want to click from there. 

But right now, the discord window is always blocking things in my screenshots.

The only times it seems to go away is if I'm successful at issuing a block command that activates another window, and then takes a screenshot. 

Is discord supposed to be minimized before a screenshot is taken? Should it be?

**Comment by psychopattt** [comment]
Discord Remote can only read commands if Discord is focused. After each command, Discord is automatically focused again to continue reading commands. You could send commands to minimize Discord, but commands can't be received in that mode and Discord Remote would stop working.

The Screenshot command does nothing to hide Discord, it only takes a screenshot. As of 1.1.0, the intended workflow to take a screenshot of a specific window (without Discord on top) is to send a bulk command to focus the window and then take a screenshot. Something like this:
```
Bulk
Focus pid 8245
Wait 50
Screenshot
```
This is quite inefficient so I'm working on a better alternative. I just committed changes to the master branch. Those changes include a new command: `Hide`, as well as an option to automatically hide Discord when you start Discord Remote. The `Hide` command changes the opacity of a specific window. The `autoHideDiscord` option sets Discord's opacity to 0 when starting Discord Remote. This allows Discord Remote to read commands while being completely invisible to screenshot commands. Be aware that, while Discord is invisible, it is still focused. This means that any keyboard inputs will be intercepted by Discord. You still need to use `Bulk` and `Focus` with `Input` or `Text` to send keyboard inputs to a specific window. The `Hide` command and `autoHideDiscord` option will be available in the next release, but the scripts are already available if you download the source code.

By the way, you can get the mouse's current position by using the `Mouse` command without parameters.
