### ISSUE TITLE
Help command feels very vague 

### ISSUE THREAD

**Issue by fiveseven808** [psychopattt/Discord-Remote#4]
The Help command is a bit confusing, especially to people unfamiliar with AHK. 

If you're going to bundle things up as an exe, maybe you could somehow reference AHK docs with a link within the help command output? 

I'd also like to see examples for each of the commands that 'help' can explain. AHK uses commas a lot. It feels like there may be some unnecessary trial and error vs if we could see an example of how all of the options are strung together for each of your commands in the help response.

**Comment by psychopattt** [comment]
I reworked the `Help` command to include a few things:
- Links to AutoHotKey's documentation where it's useful
- Examples for every command
- Better speed and reliability
- Better formatting

Those changes will be available in the next release.
